package dev.favourdevlabs.cleanthes.security;

import android.net.Uri;

/**
 * Parses otpauth:// URIs generated by services during 2FA setup.
 *
 * Full URI format:
 *   otpauth://totp/ISSUER:ACCOUNT?secret=BASE32&issuer=ISSUER&algorithm=SHA1&digits=6&period=30
 *
 * All parameters except 'secret' are optional and have sensible defaults.
 */
public final class OtpAuthParser {

    private OtpAuthParser() {}

    public static final class OtpAuthData {
        public final String secret;      // Base32 shared secret — the critical field
        public final String issuer;      // e.g. "GitHub", "Google"
        public final String accountName; // e.g. "pepe@example.com"
        public final String algorithm;   // "SHA1", "SHA256", or "SHA512"
        public final int    digits;      // almost always 6
        public final int    period;      // almost always 30

        OtpAuthData(String secret, String issuer, String accountName,
                    String algorithm, int digits, int period) {
            this.secret      = secret;
            this.issuer      = issuer;
            this.accountName = accountName;
            this.algorithm   = algorithm;
            this.digits      = digits;
            this.period      = period;
        }
    }

    /**
     * @throws IllegalArgumentException if the URI is not a valid otpauth:// URI
     *                                  or if the secret parameter is missing.
     * @throws UnsupportedOperationException if the URI is HOTP (counter-based),
     *                                       which we don't support.
     */
    public static OtpAuthData parse(String rawUri) {
        Uri uri = Uri.parse(rawUri.trim());

        if (!"otpauth".equalsIgnoreCase(uri.getScheme())) {
            throw new IllegalArgumentException(
                    "Not an otpauth URI. Got scheme: " + uri.getScheme());
        }

        // Host is either "totp" or "hotp"
        String type = uri.getHost();
        if ("hotp".equalsIgnoreCase(type)) {
            throw new UnsupportedOperationException(
                    "HOTP (counter-based) is not supported — only TOTP.");
        }
        if (!"totp".equalsIgnoreCase(type)) {
            throw new IllegalArgumentException("Unknown OTP type: " + type);
        }

        // --- secret (required) ---
        String secret = uri.getQueryParameter("secret");
        if (secret == null || secret.trim().isEmpty()) {
            throw new IllegalArgumentException("Missing required 'secret' parameter.");
        }
        secret = secret.toUpperCase().replaceAll("[=\\s]", "");

        // Validate it's actually valid Base32 by attempting a decode
        try {
            TOTPGenerator.decodeBase32(secret);
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException("Secret is not valid Base32: " + e.getMessage());
        }

        // --- issuer and account from path ---
        // Path format after leading '/': "Issuer:account@email.com"
        // or just "account@email.com" if no issuer in path
        String issuer      = null;
        String accountName = null;

        String path = uri.getPath(); // includes leading '/'
        if (path != null && path.length() > 1) {
            String label = Uri.decode(path.substring(1));
            if (label.contains(":")) {
                String[] parts = label.split(":", 2);
                issuer      = parts[0].trim();
                accountName = parts[1].trim();
            } else {
                accountName = label.trim();
            }
        }

        // Query parameter 'issuer' takes precedence over the path-derived one
        String issuerParam = uri.getQueryParameter("issuer");
        if (issuerParam != null && !issuerParam.trim().isEmpty()) {
            issuer = issuerParam.trim();
        }

        // --- algorithm (default SHA1) ---
        String algorithm = uri.getQueryParameter("algorithm");
        if (algorithm == null || algorithm.trim().isEmpty()) {
            algorithm = "SHA1";
        } else {
            algorithm = algorithm.toUpperCase().trim();
            if (!algorithm.equals("SHA1")
                    && !algorithm.equals("SHA256")
                    && !algorithm.equals("SHA512")) {
                // Unrecognised — fall back to SHA1 rather than crashing
                algorithm = "SHA1";
            }
        }

        // --- digits (default 6) ---
        int digits = 6;
        String digitsParam = uri.getQueryParameter("digits");
        if (digitsParam != null) {
            try {
                int parsed = Integer.parseInt(digitsParam.trim());
                if (parsed == 6 || parsed == 7 || parsed == 8) digits = parsed;
            } catch (NumberFormatException ignored) {}
        }

        // --- period (default 30) ---
        int period = 30;
        String periodParam = uri.getQueryParameter("period");
        if (periodParam != null) {
            try {
                int parsed = Integer.parseInt(periodParam.trim());
                if (parsed > 0) period = parsed;
            } catch (NumberFormatException ignored) {}
        }

        return new OtpAuthData(secret, issuer, accountName, algorithm, digits, period);
    }
}

