package dev.favourdevlabs.cleanthes.domain.otp

import java.net.URI
import java.net.URLDecoder

/**
 * Parses otpauth:// URIs generated by services during 2FA setup.
 * Pure JVM — no Android imports.
 *
 * Full URI format:
 *   otpauth://totp/ISSUER:ACCOUNT?secret=BASE32&issuer=ISSUER&algorithm=SHA1&digits=6&period=30
 */
object OtpAuthParser {

    data class OtpAuthData(
        val secret: String,
        val issuer: String?,
        val accountName: String?,
        val algorithm: String,
        val digits: Int,
        val period: Int,
    )

    @Throws(IllegalArgumentException::class, UnsupportedOperationException::class)
    fun parse(rawUri: String): OtpAuthData {
        val uri = URI(rawUri.trim())

        if (!"otpauth".equals(uri.scheme, ignoreCase = true))
            throw IllegalArgumentException("Not an otpauth URI. Got scheme: ${uri.scheme}")

        val type = uri.host
        if ("hotp".equals(type, ignoreCase = true))
            throw UnsupportedOperationException("HOTP (counter-based) is not supported — only TOTP.")
        if (!"totp".equals(type, ignoreCase = true))
            throw IllegalArgumentException("Unknown OTP type: $type")

        val params = parseQueryParams(uri.rawQuery)

        var secret = params["secret"]
            ?.takeIf { it.trim().isNotEmpty() }
            ?: throw IllegalArgumentException("Missing required 'secret' parameter.")
        secret = secret.uppercase().replace(Regex("[=\\s]"), "")

        try {
            TOTPGenerator.decodeBase32(secret)
        } catch (e: IllegalArgumentException) {
            throw IllegalArgumentException("Secret is not valid Base32: ${e.message}")
        }

        var issuer: String? = null
        var accountName: String? = null
        val path = uri.path
        if (path != null && path.length > 1) {
            val label = URLDecoder.decode(path.substring(1), "UTF-8")
            if (label.contains(":")) {
                val parts = label.split(":", limit = 2)
                issuer      = parts[0].trim()
                accountName = parts[1].trim()
            } else {
                accountName = label.trim()
            }
        }

        params["issuer"]?.trim()?.takeIf { it.isNotEmpty() }?.let { issuer = it }

        val algorithm = params["algorithm"]
            ?.trim()
            ?.uppercase()
            ?.takeIf { it == "SHA256" || it == "SHA512" }
            ?: "SHA1"

        val digits = params["digits"]?.trim()?.toIntOrNull()
            ?.takeIf { it == 6 || it == 7 || it == 8 } ?: 6

        val period = params["period"]?.trim()?.toIntOrNull()
            ?.takeIf { it > 0 } ?: 30

        return OtpAuthData(secret, issuer, accountName, algorithm, digits, period)
    }

    private fun parseQueryParams(rawQuery: String?): Map<String, String> {
        if (rawQuery.isNullOrEmpty()) return emptyMap()
        return rawQuery.split("&")
            .mapNotNull { pair ->
                val idx = pair.indexOf('=')
                if (idx < 0) null
                else {
                    val key   = URLDecoder.decode(pair.substring(0, idx), "UTF-8")
                    val value = URLDecoder.decode(pair.substring(idx + 1), "UTF-8")
                    key to value
                }
            }
            .toMap()
    }
}

